### ISSUE TITLE
Can we Use WebSocket to Reduce Chrome Uses

### ISSUE THREAD

**Issue by biplob86429** [chrishubert/whatsapp-api#50]
Sir,
Chrome Take High Memory resources. some plugings using  WebSocket. Not running Selenium or Chromimum saves you like half a gig of ram. How it can be possible here ?

**Comment by chrishubert** [comment]
Hello, I agree - Chromium indeed uses a lot of resources.
Yet, we are "just" a wrapper for the https://github.com/pedroslopez/whatsapp-web.js repository.
Since their complete logic is based on Chromium, there is no plan of moving forward otherwise.
Now the websockets could be an alternative to the WebHook which is worth exploring. But still using Chromium 😅

**Comment by chrishubert** [comment]
I'm closing the issue, please reopen a new one if necessary
